# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Rivi Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Rivi Demo
  pod 'SDWebImage'

  target 'Rivi DemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
